//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapsManagerDataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int RingBinderID { get; set; }
    
        public virtual RingBinder RingBinder { get; set; }
    }
}
